apiVersion: v2
name: core
description: A Helm chart for codex.bot core
type: application
version: 0.2.6
appVersion: 0.0.1

dependencies:
  - name: mongodb
    version: 12.1.x
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: rabbitmq
    version: 10.1.x
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
    
